### ISSUE TITLE
Question about missing packages

### ISSUE THREAD

**Issue by LZL-CS** [mlvlab/UP-NeRF#1]
Hi, thanks for sharing your awesome work. When I run the code of `sh ./preprocess/preprocess_all.sh brandenburg_gate`, I got the error:
<img width="1399" alt="image" src="https://github.com/mlvlab/UP-NeRF/assets/54640259/df96f4b4-a8ad-4e61-bc65-f1f5b8b87376">

It seems that related to the missing packages `extractor` and `util`. I appreciate any help you can provide and Happy New Year!

**Comment by LZL-CS** [comment]
I think the `dpt` module is also missing:
<img width="1041" alt="image" src="https://github.com/mlvlab/UP-NeRF/assets/54640259/a6707690-0c53-43b3-9663-b4c6f7c03616">

**Comment by cmh1027** [comment]
It seems submodules were missed out during migration. We updated the repo!
