### ISSUE TITLE
On My Own Dataset

### ISSUE THREAD

**Issue by TwiceMao** [mlvlab/UP-NeRF#2]
@cmh1027 cmh1027  Thank you for your excellent work. Now, I want to run your code on a custom dataset, but I am encountering some difficulties with the dataloader part of your code. My dataset is of a certain indoor scene and includes some color images, with known 'near' and 'far' scene parameters, and known camera intrinsics. Due to the uniqueness of our dataset, it cannot be successfully processed with COLMAP. However, when I was reading your code, it utilizes data processed by COLMAP and has some other settings, so could you please give me some advice? Thank you!

**Comment by cmh1027** [comment]
@TwiceMao Hello. I updated the dataset file for custom datasets. You can check it in README. (You have to specify the focal length in pixel just as COLMAP, not mm)

p.s. just so you know, our model only supports forward-facing scene (not 360 degree)

**Comment by TwiceMao** [comment]
Big Thanks!

**Comment by TwiceMao** [comment]
@cmh1027  I need to compare your method with my custom data set. But I encountered difficulties when doing test-time-optimization and evaluation. Could you please provide me with convenience? thank you!

**Comment by cmh1027** [comment]
@TwiceMao Test-time optimization requires GT camera poses (you can refer to supplementary material) because it is only for reporting metrices of validation images. Based on your first comment, it seems that you don't have GT poses so I guess that doing TTO on your dataset is not possible. If you still want me to update the code, please leave the comment.

**Comment by TwiceMao** [comment]
@cmh1027  
Sorry, I didn't provide complete information. We have GT (Ground Truth) camera poses ,mesh and depth maps. Since our dataset is a synthetic dataset, we have GT camera poses available. However, due to the challenging settings of the dataset, traditional Structure from Motion methods cannot function properly. So I wish you to update the code. Big thanks!

**Comment by cmh1027** [comment]
@TwiceMao I updated the code, but didn't test it because currently there's no GPU left due to ECCV. Let me know if any error occurs.

**Comment by TwiceMao** [comment]
@cmh1027   Thanks, I will test soon! And I will tell you the error if there is.
